image:
  - Visual Studio 2017
  - Ubuntu

build: off
configuration:
  - test
  - test2
init:
  - sh: printenv
  - cmd: set


version: 0.0.1.{build}

skip_commits:
  files:
    - README.md

environment:
  my_variable:
    secure: JZqRfVvRyjoXGRetu7F8tzJrWQpjbywVnypazm+5rYE=    
# Install Pester for testing
install:
  - ps: $PSVersionTable
  - ps: Install-Module Pester -Scope CurrentUser -Force -SkipPublisherCheck
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: mkdir %USERPROFILE%\.aws
  - cmd: appveyor-tools\secure-file -decrypt etc\config.enc -out %USERPROFILE%\.aws\config -secret %my_secret%
  #- cmd: appveyor-tools\secure-file -decrypt etc\credentials.enc -out %USERPROFILE%\.aws\credentials -secret %my_secret%
  - sh: mkdir $HOME/.aws
  - sh: ./appveyor-tools/secure-file -decrypt etc/config.enc -out $HOME/.aws/config -secret $my_secret
  #- sh: ./appveyor-tools/secure-file -decrypt etc/credentials.enc -out $HOME/.aws/credentials -secret $my_secret


